// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8u9qscWNbGKZ7Lu5ArFvVYUEbxtizDLQ',
    appId: '1:711496257874:web:51a336e20e636c9a296a8b',
    messagingSenderId: '711496257874',
    projectId: 'efreim2todonest',
    authDomain: 'efreim2todonest.firebaseapp.com',
    storageBucket: 'efreim2todonest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_cAIWJTe39Bx-o6QXS4HZS1q-2K93nBw',
    appId: '1:711496257874:ios:3cf51ca68f2975a4296a8b',
    messagingSenderId: '711496257874',
    projectId: 'efreim2todonest',
    storageBucket: 'efreim2todonest.firebasestorage.app',
    iosBundleId: 'com.example.todonest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_cAIWJTe39Bx-o6QXS4HZS1q-2K93nBw',
    appId: '1:711496257874:ios:3cf51ca68f2975a4296a8b',
    messagingSenderId: '711496257874',
    projectId: 'efreim2todonest',
    storageBucket: 'efreim2todonest.firebasestorage.app',
    iosBundleId: 'com.example.todonest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8u9qscWNbGKZ7Lu5ArFvVYUEbxtizDLQ',
    appId: '1:711496257874:web:8f0801f78f965f4d296a8b',
    messagingSenderId: '711496257874',
    projectId: 'efreim2todonest',
    authDomain: 'efreim2todonest.firebaseapp.com',
    storageBucket: 'efreim2todonest.firebasestorage.app',
  );
}
